# Generated by Django 2.2.4 on 2020-08-25 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='TrobuleMaker', max_length=255),
        ),
    ]
